server:
  port: 8080
  forward-headers-strategy: framework
  address: 0.0.0.0   # 监听所有网卡

spring:
  profiles:
    active: dev

  application:
    name: verdant-edge

  datasource:
    url: ${verdant.datasource.url}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${verdant.datasource.username}
    password: ${verdant.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      # 核心连接池参数
      maximum-pool-size: 20      # 最大连接数
      minimum-idle: 10           # 最小空闲连接数
      connection-timeout: 30000  # 获取连接超时时间（ms）
      idle-timeout: 600000       # 空闲连接回收时间（ms）
      max-lifetime: 1800000      # 连接最大生命周期（ms）

  thymeleaf:
    check-template-location: false

  mail:
    host: ${verdant.mail.host}
    port: ${verdant.mail.port}
    username: ${verdant.mail.username}
    password: ${verdant.mail.password}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.timeout: 5000
      mail.smtp.connectiontimeout: 5000

# MP 配置
mybatis-plus:
  # configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 SQL 日志，方便调试
  global-config:
    db-config:
      id-type: auto # 主键策略：数据库自增

logging:
  level:
    edge:
      verdant:
        mapper: debug
        service: info
        controller: info

aliyun:
  dashscope:
    api-key: ${verdant.aliyun.access-key-id}
    model: qwen-flash
    timeout: 30000

verdant:
  data-retention:
    machine-record-days: 90
    machine-camera-days: 90

  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: verdant-edge-jwt-secret-key-2026-secure
    # 设置jwt过期时间 83天
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

  alioss: # oss
    endpoint: ${verdant.alioss.endpoint}
    access-key-id: ${verdant.alioss.accessKeyId}
    access-key-secret: ${verdant.alioss.accessKeySecret}
    bucket-name: ${verdant.alioss.bucket-name}